PracticeApp/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PracticeApp.HttpServices;
using PracticeApp.Models;
using PracticeApp.RequestModels;
using PracticeApp.Services;
using PracticeApp.Utils;

namespace PracticeApp.Controllers
{
    public class ItemController : Controller
    {
        private readonly ItemService _service;
        private readonly HttpService _httpService;
        public ItemController(ItemService service, HttpService httpService)
        {
            _httpService = httpService;
            _service = service;
        }

        // GET: Item
        public async Task<IActionResult> Index()
        {
            string parameters = $"item";
            var item = await _httpService.GetObjectFromJson<ItemRoot>(parameters);

            if (item != null)
            {
                Console.WriteLine("success in the Item controller");
                foreach (var element in item.ListOfItems)
                {
                    Console.WriteLine($"{element.ItemNo} && {element.SKU}");
                }
            }
            else
            {
                Console.WriteLine("Somethings gone wrong in Item Controller");
            }

            var itemsList = await _service.GetItemModels();

            return itemsList != null
                ? View(itemsList)
                : NotFound();
        }

        // GET: Item/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            return ControllerErrorChecker.CheckDbAndId(id, _service.Context.ItemModel) == false
                ? View(await _service.GetDetails(id))
                : NotFound();
        }

        // GET: Item/Create
        public IActionResult Create()
        {
         
            ViewData["SKUCode"] = new SelectList(_service.Context.ProductModel, "SKUCode", "SKUCode");
            ViewData["GRN"] = new SelectList(_service.Context.Set<ReceiptModel>(), "GRN", "GRN");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemNo,GRN,Quantity,SKUCode")] ItemModel itemModel, int? id)
        {
            if (ModelState.IsValid)
            {
                if (id != null)
                {
                    itemModel.GRN = (int)id;
                }
                await _service.CreateItemModel(itemModel);
                // I like this better than getting the refferer from the headers as its less error prone and feels more secure
                return RedirectToRoute("default", new { controller = "Receipt", action = "Index" });

            }
            ViewData["SKUCode"] = new SelectList(_service.Context.ProductModel, "SKUCode", "SKUCode", itemModel.SKUCode);
            ViewData["GRN"] = new SelectList(_service.Context.Set<ReceiptModel>(), "GRN", "GRN", itemModel.GRN);

            return View(itemModel);
        }

        // GET: Item/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (ControllerErrorChecker.CheckDbAndId(id, _service.Context.ItemModel))
            {
                return NotFound();
            }
            var itemModel = await _service.FindItemAsync(id);
            if (itemModel != null)
            {
                ViewData["SKUCode"] = new SelectList(_service.Context.ProductModel, "SKUCode", "SKUCode", itemModel.SKUCode);
                ViewData["GRN"] = new SelectList(_service.Context.Set<ReceiptModel>(), "GRN", "GRN", itemModel.GRN);
                return View(itemModel);
            }
            return NotFound();
        }

        // POST: Item/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemNo,GRN,Quantity,SKUCode")] ItemModel itemModel)
        {
            if (id != itemModel.ItemNo)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                await _service.UpdateItemModel(itemModel);
                return RedirectToAction(nameof(Index));
                  
            }
            ViewData["SKUCode"] = new SelectList(_service.Context.ProductModel, "SKUCode", "SKUCode", itemModel.SKUCode);
            ViewData["GRN"] = new SelectList(_service.Context.Set<ReceiptModel>(), "GRN", "GRN", itemModel.GRN);
            return View(itemModel);
        }

        // GET: Item/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            return ControllerErrorChecker.CheckDbAndId(id, _service.Context.ItemModel) == false
                ? View(await _service.GetItemModelAsync(id))
                : NotFound();
        }

        // POST: Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (ControllerErrorChecker.CheckDbAndId(_service.Context.ItemModel))
            {
                return Problem("Entity set 'PracticeAppDbContext.ItemModel'  is null.");
            }

            await _service.ConfirmDelete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

PracticeApp/Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using PracticeApp.HttpServices;
using PracticeApp.Models;
using PracticeApp.RequestModels;
using PracticeApp.Services;
using PracticeApp.Utils;

namespace PracticeApp.Controllers
{
    public class LocationController : Controller
    {
        private readonly LocationService _locationService;
        private readonly HttpService _httpService;

        public LocationController(LocationService service, HttpService httpService)
        {
            _locationService = service;
            _httpService = httpService;
        }
        // GET: Location
        public async Task<IActionResult> Index(string? id)
        {
            string parameters = $"location";
            var location = await _httpService.GetObjectFromJson<LocationRoot>(parameters);

            if (location != null)
            {
                Console.WriteLine("success in the location controller");
                foreach (var item in location.List)
                {
                    Console.WriteLine($"Location Weight is : {item.Weight} && Height is {item.Height}");
                }
            }
            else
            {
                Console.WriteLine("Somethings gone wrong in location Controller");
            }

            if (string.IsNullOrEmpty(id))
            {
                var locationList = await _locationService.GetLocationList();
                return locationList != null
                    ? View(locationList)
                    : Problem("Entity set 'PracticeAppDbContext.LocationModel'  is null.");
            }
            var locationSearchList = await _locationService.GetLocationSearchList(id);
            return locationSearchList != null
                ? View(locationSearchList)
                : Problem("Entity set 'PracticeAppDbContext.LocationModel'  is null.");

        }

        // GET: Location/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (ControllerErrorChecker.CheckDbAndId(id, _locationService.Context.LocationModel))
            {
                return NotFound();
            }

            var locationModel = await _locationService.GetLocationDetails(id);

            return locationModel != null
                ? View(locationModel)
                : NotFound();
        }

        // GET: Location/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LocationId,Length,Height,Width")] LocationModel locationModel)
        {
            if (ModelState.IsValid)
            {
                await _locationService.CreateLocation(locationModel);
                return RedirectToAction(nameof(Index));
            }
            return View(locationModel);
        }

        // GET: Location/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (ControllerErrorChecker.CheckDbAndId(id, _locationService.Context.LocationModel))
            {
                return NotFound();
            }

            var locationModel = await _locationService.GetLocationAsync(id);
            return locationModel != null
                ? View(locationModel)
                : NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("LocationId,Length,Height,Width")] LocationModel locationModel)
        {
            if (id != locationModel.LocationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _locationService.EditLocation(id, locationModel);
                return RedirectToAction(nameof(Index));
            }
            return View(locationModel);
        }

        // GET: Location/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteItem(int? id)
        {
            if (id != null)
            {
                await _locationService.DeleteItem(id);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string id)
        {
            return ControllerErrorChecker.CheckDbAndId(id, _locationService.Context.LocationModel) == false
                ? View(await _locationService.GetLocation(id))
                : NotFound();
        }

        // POST: Location/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (ControllerErrorChecker.CheckDbAndId(_locationService.Context.LocationModel))
            {
                return Problem("Entity set 'PracticeAppDbContext.LocationModel'  is null.");
            }

            await _locationService.ConfirmDelete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

PracticeApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using PracticeApp.HttpServices;
using PracticeApp.Models;
using PracticeApp.RequestModels;
using PracticeApp.Services;
using PracticeApp.Utils;

namespace PracticeApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductService _productService;
        private readonly HttpService _httpService;

        public ProductController(ProductService service, HttpService httpservice)
        {
            _productService = service;
            _httpService = httpservice;
        }

        // GET: Product
        public async Task<IActionResult> Index(string sku)
        {
            string url = $"product";
            var product = await _httpService.GetObjectFromJson<ProductRoot>(url);

            if (product != null)
            {
                Console.WriteLine("success in the product controller");
                foreach (var item in product.List)
                {
                    Console.WriteLine($"Product Width is : {item.Width} && Sku is : {item.SKU}");
                }
            }
            else
            {
                Console.WriteLine("this has messed up somewhere in the product controller");
            }

            if (!string.IsNullOrEmpty(sku))
            {
                var searchProductList = await _productService.SearchForProducts(sku);
                return searchProductList != null ?
                            View(searchProductList) :
                            Problem("Entity set 'PracticeAppDbContext.ProductModel'  is null.");
            }

            var productList = await _productService.GetProducts();
            return productList != null ?
                        View(productList) :
                        Problem("Entity set 'PracticeAppDbContext.ProductModel'  is null.");

        }
        // GET: Product/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var productModel = await _productService.GetProductBySku(id);

                return id != null || productModel != null
                    ? View(productModel)
                    : NotFound();
            }
            return NotFound();
        }
        // GET: Product/Create
        public IActionResult Create()
        {
            return View();
        }
        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SKUCode,Description,Length,Height,Width,Weight")] ProductModel productModel)
        {
            if (ModelState.IsValid)
            {
                await _productService.CreateProductModel(productModel);
                return RedirectToAction(nameof(Index));
            }
            return View(productModel);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var product = await _productService.GetProductAsync(id);
                return product != null
                    ? View(product)
                    : NotFound();
            }
            return NotFound();
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SKUCode,Description,Length,Height,Width,Weight")] ProductModel productModel)
        {
            if (id != productModel.SKUCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _productService.EditProductModel(productModel);
                return RedirectToAction(nameof(Index));
                    
            }
            return View(productModel);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var product = await _productService.GetProductBySku(id);

                return product != null
                    ? View(product)
                    : NotFound();
            }
            return NotFound();
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (ControllerErrorChecker.CheckDbAndId(id, _productService.Context))
            {
                return Problem("Entity set 'PracticeAppDbContext.ProductModel'  is null.");
            }

            await _productService.ConfirmDelete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

PracticeApp/Views/Shared/_ItemProductCard.cshtml
@model IEnumerable<PracticeApp.Models.ItemModel>

@{
}

<!-- Displays all the products stored at a particular location -->
@foreach (var item in Model)
{
    @if (item.LocationId != null)
    {
        <div class="card custom-card-style">

            @if (item.Product != null)
            {
                <form>
                    <input class="card-img-top mt-2"
                           src="@item.Product.ImageURL" alt="~/images/placeholder.png"
                           type="image"
                           asp-controller="Product"
                           asp-action="Details"
                           asp-route-id="@item.SKUCode" />
                </form>
            }
            else
            {
                <form>
                    <input class="card-img-top mt-2"
                           src="~/images/placeholder.png
                           type="image"
                           asp-controller="Product"
                           asp-action="Details"
                           asp-route-id="@item.SKUCode" />
                </form>
            }

            <div class="card-body">
                <h5 class="card-title">Product</h5>

                <div class="text-black">
                    @Html.DisplayNameFor(model => model.Receipt) :
                    @if (item.Receipt != null)
                    {
                        @Html.DisplayFor(modelItem => item.Receipt.GRN)
                    }

                </div>
                <div class="text-black">
                    @Html.DisplayNameFor(model => model.Quantity) :
                    @Html.DisplayFor(modelItem => item.Quantity)
                </div>
                <div class="text-black">
                    @Html.DisplayNameFor(model => model.Product) :
                    @if (item.Product != null)
                    {
                        @Html.DisplayFor(modelItem => item.Product.SKUCode)
                    }
                </div>

                <div class="text-black">
                    @Html.DisplayNameFor(model => model.LocationId) :
                    @if (item.Product != null)
                    {
                        @Html.DisplayFor(modelItem => item.LocationId)
                    }
                </div>
                <div class="mt-2">
                    <a class="btn btn-primary" asp-controller="ItemLocation" asp-action="Edit" asp-route-id="@item.ItemNo">Edit</a>
                    <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.ItemNo">Details</a>
                    <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.ItemNo">Delete</a>
                </div>
              
            </div>


        </div>
    }
   
}

PracticeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticeApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticeApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!-- Home -->
                        <li class="nav-item">
                            <a class="nav-link dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!-- Privacy -->
                        <li class="nav-item">
                            <a class="nav-link dropdown-item" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <!--   Pre-alert -->
                        <li class="nav-item dropdown">

                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Pre-alert
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li>
                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Trader SKU's</a>
                                </li>
                                <li>
                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Location" asp-action="Index">Warehouse traders</a>
                                </li>
                                <li>
                                    
                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Receipt" asp-action="Index">Recieipt advice maintance</a>
                                </li>
                            </ul>
                        </li>
                        <!--  Receive Process -->
                        <li class="nav-item dropdown">

                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Receive Process
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li>
                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">WIP</a>
                                </li>
                                <li>
                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Receipt" asp-action="Index">Receipt advice history</a>
                                </li>
                            </ul>
                        </li>
                        <!-- Inventory -->
                        <li class="nav-item dropdown">

                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Inventory
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li>
                                    <a data-bs-toggle="modal" data-bs-target="#skuModal" class="nav-link dropdown-item" asp-area="">SKU Enquiry</a>
                                </li>
                                <li>

                                    <a data-bs-toggle="modal" data-bs-target="#locationModal" class="nav-link dropdown-item" asp-area="">Location Enquiry</a>
                               
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Item" asp-action="Index">Location adjustment</a>
                                </li>

                            </ul>
                        </li>
                        <!-- ill get round to the Dispatch process later -->
                        <li class="nav-item dropdown">
                          
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Despatch Process
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li>
                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">WIP</a>
                                </li>
                                <li>
                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Receipt" asp-action="Index">Receipt advice history</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                </li>

                            </ul>
                        </li>
                    </ul>

                   
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PracticeApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<!-- Modal for sku searching. Placed here to save a seprate view -->
<div class="modal fade" id="skuModal" tabindex="-1" aria-labelledby="skuModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen-sm-down">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="skuModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">

                    <form method="post">
                        <label for="SKUCode">SKU code</label>
                        <input type="text" id="sku" name="sku" placeholder="Enter your SKU code" />
                        <input type="submit" asp-action="Index" asp-controller="Product" id="sku" name="sku" />
                    </form>
                  
                </div>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<!-- Modal for location searching. Placed here to save a seprate view -->
<div class="modal fade" id="locationModal" tabindex="-1" aria-labelledby="locationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen-sm-down">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="locationModalLabel">Location search</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">

                    <form method="post">
                        <label for="LocationId">Location id</label>
                        <input type="text" id="id" name="id" placeholder="Enter the location id" />
                        <input class="btn btn-primary" type="submit" asp-action="Index" asp-controller="Location" id="id" name="id" />
                    </form>

                </div>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>