SoccerStatsNew/Models/LeagueDataDto.cs
using SoccerStatsData;

namespace SoccerStatsNew.Models
{
    public class LeagueDataDto
    {
        public LeagueModel League { get; set; }
        public SeasonModel Season { get; set; }

        public LeagueDataDto(LeagueModel id, SeasonModel year)
        {
            League = id;
            Season = year;
        }
       
    }
}

SoccerStatsNew/Models/PlayerData.cs
using SoccerStatsData.RequestModels;

namespace SoccerStatsNew.Models
{
    public class PlayerData
    {
        public List<PlayerRequestFile> Response { get; set; } = new List<PlayerRequestFile>();
        public int MyProperty { get; set; }
    }
}

SoccerStatsNew/Controllers/FixtureController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using SoccerStatsNew.DbServices;

namespace SoccerStatsNew.Controllers
{
    public class FixtureController : Controller
    {
        private readonly FixtureService _Service;

        public FixtureController(FixtureService service)
        {
            _Service = service;
        }

        public async Task<IActionResult> Index(int team, string year)
        {
            var fixture = await _Service.GetTeamFixtures(team, year);
            return fixture != null
                ? View(fixture.Response)
                : NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Fixtures(int leagueId)
        {
            var fixture = await _Service.GetLeagueFixtures(leagueId, "2023");

            return fixture != null
                ? View(fixture.Response)
                : NotFound();
        }
    }
}

SoccerStatsNew/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SoccerStatsData;
using SoccerStatsNew.Services;
using System.Diagnostics;

namespace SoccerStatsNew.Controllers
{
    public class HomeController : Controller
    {
        private readonly LeagueDbService _leagueDbService;
        private readonly CountryDbService _countryService;

        public HomeController(CountryDbService service, LeagueDbService seasonDbService)
        {
            _leagueDbService = seasonDbService;
            _countryService = service;
        }

        public async Task<IActionResult> Index(string code)
        {
            if (string.IsNullOrEmpty(code))
            {
                var countries = await _countryService.GetAllCountriesToList();
                return countries != null
                       ? View(countries)
                       : NotFound();
            }
            var country = await _countryService.GetCountryDetails(code);
            
            return country != null 
                ? View(country) 
                : NotFound();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<JsonResult> ServerFiltering_Countries(string text)
        {
            var countries = await _countryService.GetCountrys(text);

            return countries != null
                ? Json(countries)
                : Json("");
        }
    }
}

SoccerStatsNew/Controllers/LeagueController.cs
using Azure.Core;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using SoccerStatsData.RequestModels.PredictionRequestFiles;
using SoccerStatsNew.DbServices;
using SoccerStatsNew.Services;
using UtilityLibraries;

namespace SoccerStatsNew.Controllers
{
    public class LeagueController : Controller
    {
        private readonly LeagueDbService _leagueService;

        public LeagueController(LeagueDbService leagueService)
        {
            _leagueService = leagueService;
        }

        public async Task<IActionResult> Index(string country)
        {
            var leagues = await _leagueService.GetLeagueDetails(country);

            return leagues != null
                ? View(leagues)
                : NotFound();
        }

        public async Task<IActionResult> Details(int league, string year)
        {
            var leagueResponse = await _leagueService.ConstructLeagueData(league, year);

            return leagueResponse != null
                ? View(leagueResponse)
                : NotFound();
        }

        public async Task<IActionResult> Team(int team, string year)
        {
            var yearNumber = int.Parse(year);
            var individualTeam = await _leagueService.GetTeam(team, yearNumber);

            return individualTeam != null 
                ? View(individualTeam) 
                : NotFound();
            
        }

        public async Task<JsonResult> Teams_Read([DataSourceRequest] DataSourceRequest request, int league, string year)
        {
            var teamResponse = await _leagueService.GetTeamModels(league, year);

            return teamResponse != null
                ? Json(teamResponse.ToDataSourceResult(request))
                : Json(null);
        }
    }
}

SoccerStatsNew/Controllers/LeagueTableController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using SoccerStatsNew.DbServices;

namespace SoccerStatsNew.Controllers
{
    public class LeagueTableController : Controller
    {
        private readonly LeagueTableService _tableService;
        public LeagueTableController(LeagueTableService service)
        {
            _tableService = service;    
        }
        public async Task<IActionResult> Index(int leagueid, string year)
        {
            var table = await _tableService.GetLeagueTable(leagueid, year);
           
            return table != null 
                    ? View(table) 
                    : NotFound();
        }
        
    }
}

SoccerStatsNew/Controllers/PlayerController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using SoccerStatsNew.DbServices;

namespace SoccerStatsNew.Controllers
{
    public class PlayerController : Controller
    {
        private readonly PlayerService _playerService;
        public PlayerController(PlayerService service)
        {
            _playerService = service;
        }
        public async Task<ActionResult> Index(int team, string season, int league)
        {
            var players = await _playerService.GetPlayers(team, season, league);
            
            return players != null 
                ? View(players) 
                : NotFound();
        }
    }
}

SoccerStatsNew/Controllers/PredictionController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using SoccerStatsData.RequestModels.PredictionRequestFiles;
using UtilityLibraries;

namespace SoccerStatsNew.Controllers
{
    public class PredictionController : Controller
    {
        private readonly WebService _webService;

        public PredictionController(WebService webService)
        {
            _webService = webService;
        }

        public IActionResult Index(int? fixture)
        {
            string urlParams = $"predictions?fixture={fixture}";

            var predictions = JsonHelper.GetObjectFromJsonFile<PredictionRoot>("Test/predictions.json");

            return predictions != null
                ? View(predictions.Response[0])
                : NotFound();
        }

        public IActionResult Last_Five_Read([DataSourceRequest] DataSourceRequest request)
        {
            var predictions = JsonHelper.GetObjectFromJsonFile<PredictionRoot>("Test/predictions.json");

            if (predictions != null)
            {
                return Json(predictions.Response[0].HeadToHeadStats.ToDataSourceResult(request));
            }

            return Json(null);
        }
    }
}

SoccerStatsNew/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;

namespace SoccerStatsNew.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SoccerStatsNew/Views/Home/Index.cshtml
@model IEnumerable<SoccerStatsData.CountryModel>

<div class="k-d-flex k-justify-content-center" style="padding-top: 54px;">
    <div class="k-w-300">
        <label for="countries">Choose a country to view leagues:</label>
        @(Html.Kendo().AutoComplete()
                      .Name("countries")
                      .DataTextField("Name")
                      .FooterTemplate("Total <strong>#: instance.dataSource.total() #</strong> items found")
                      .Template("<div class=\"container\"> " 
                              + "<div> "
                              + " <img src=\"#:data.FlagURL#\">"
                              + " </div>  <span class=\"k-state-default\"><h3>#: data.Name #</h3><p>#: data.CountryCode #</p></span> </div>")
                      .Filter("contains")
                      .DataSource(source =>
                      {
                            source.Read(read =>
                            {
                                read.Action("ServerFiltering_Countries", "Home")
                                .Data("onAdditionalData");
                            })
                        .ServerFiltering(true);
                      })
                      .HtmlAttributes(new { style = "width: 100%;" })
                      .Placeholder("Search for a country...")
                      .Events(e =>
                      {
                         e.Select("onSelect");
                      })
        )
        <div class="demo-hint">Start typing the name of a country</div>
    </div>
</div>

<div id="countries">
    <div class="row container">

        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <div class="k-card k-card-horizontal k-text-center">
                    <div class="k-card-header">
                        <h5 class="k-card-title">@item.Name</h5>
                        <img src="@item.FlagURL" alt="undefined" class="k-card-image">
                    </div>
                    <div class="k-card-actions k-card-actions-vertical k-card-actions-stretched">

                        <form method="post">
                            <button class="k-button k-button-flat-primary k-button-flat k-button-md k-rounded-md"
                                    asp-action="Index"
                                    asp-controller="League"
                                    asp-route-country="@item.Name">
                                View Leagues
                            </button>
                        </form>
                        <span class="k-card-action">
                            
                            
                        </span>
                    </div>
                </div>
            }
        }
    </div>
</div>

@section styles {
    <link rel="stylesheet" href="~/css/countries.css" />
}

@section scripts {
    <script src="~/js/countries.js"> </script>
}

SoccerStatsNew/Views/League/Details.cshtml
@model SoccerStatsNew.Models.LeagueDataDto

@{
    var LeagueModel = Model.League;
    var SeasonModel = Model.Season;
}

<div class="k-card k-card-horizontal">
    <div class="image">

        <div>
            <img src="@LeagueModel.Country.FlagURL" alt="not found" class="k-card-image" />
        </div>
        <div>
            <img src="@LeagueModel.LogoURL" alt="not found" class="k-card-image" />
        </div>
        


    </div>
    <div class="k-vbox k-column">
        <div class="k-card-header">
            <h5 class="k-card-title"><b>@LeagueModel.Name</b></h5>
            <h6 class="k-card-subtitle">Competion type <b>@LeagueModel.Type</b></h6>
            <h6 class="k-card-subtitle">Country: <b>@LeagueModel.Country.Name</b></h6>
            <h6 class="k-card-subtitle">Start date: <b>@SeasonModel.StartDate</b></h6>
            <h6 class="k-card-subtitle">End date: <b>@SeasonModel.EndDate</b></h6>
            
        </div>
        <div class="k-card-body">
            @(Html.Kendo().ListView<SoccerStatsData.TeamResponse>()
                .Name("listView")
                .TagName("div")
                .ClientTemplateId("teams")
                .DataSource(dataSource => dataSource
                .Ajax()
                .Read(read => read.Action("Teams_Read", "League", new { league = LeagueModel.LeagueId, year = SeasonModel.Year }))
                .PageSize(24)
                )
                .Pageable(pageable => pageable
                .Refresh(true)
                .ButtonCount(5)
                )
                .Selectable(ListViewSelectionMode.Single)
                .Events(events => events.Change("onChange"))
                )

        </div>
        <div class="k-card-actions k-card-actions-stretched k-card-actions-horizontal">
          
            @if (SeasonModel.Standings)
            {
                <kendo-button name="#standings"
                              deferred=true
                              on-click="function(){ location.href = '/LeagueTable?leagueid=@LeagueModel.LeagueId&year=@SeasonModel.Year' }"
                              icon="k-icon k-i-calendar">
                    Tables
                </kendo-button>
            }
            @if (SeasonModel.TopScorers)
            {
                <kendo-button name="#top-score"
                              deferred=true
                              on-click="function(){ location.href = '/LeagueTable?leagueid=@LeagueModel.LeagueId&year=@SeasonModel.Year' }"
                              icon="k-icon k-i-calendar">
                    Top scorerer
                </kendo-button>
            }
            @if (SeasonModel.Players)
            {
                <kendo-button name="#players"
                              deferred=true
                              on-click="function(){ location.href = '/LeagueTable?leagueid=@LeagueModel.LeagueId&year=@SeasonModel.Year' }"
                              icon="k-icon k-i-calendar">
                    Players
                </kendo-button>
            }
            @if (SeasonModel.TopAssists)
            {
                <kendo-button name="#top-assists"
                              deferred=true
                              on-click="function(){ location.href = '/LeagueTable?leagueid=@LeagueModel.LeagueId&year=@SeasonModel.Year' }"
                              icon="k-icon k-i-calendar">
                    top assits
                </kendo-button>
            }
            @if (SeasonModel.TopCards)
            {
                <kendo-button name="#top-cards"
                              deferred=true
                              on-click="function(){ location.href = '/LeagueTable?leagueid=@LeagueModel.LeagueId&year=@SeasonModel.Year' }"
                              icon="k-icon k-i-calendar">
                    top cards
                </kendo-button>
              
            }
            @if (SeasonModel.Injuries)
            {
                <kendo-button name="#injuries"
                              deferred=true
                              on-click="function(){ location.href = '/LeagueTable?leagueid=@LeagueModel.LeagueId&year=@SeasonModel.Year' }"
                              icon="k-icon k-i-calendar">
                    injuries
                </kendo-button>
            }
            @if (SeasonModel.Predictions)
            {
                <kendo-button name="#predictions"
                              deferred=true
                              on-click="function(){ location.href = '/LeagueTable?leagueid=@LeagueModel.LeagueId&year=@SeasonModel.Year' }"
                              icon="k-icon k-i-calendar">
                    Predictions
                </kendo-button>
            }
            @if (SeasonModel.Odds)
            {
                <kendo-button name="#odds"
                              deferred=true
                              on-click="function(){ location.href = '/LeagueTable?leagueid=@LeagueModel.LeagueId&year=@SeasonModel.Year' }"
                              icon="k-icon k-i-calendar">
                    Odds
                </kendo-button>
            }
        </div>
       
    </div>
</div>

<!-- might have to throw the league through here too -->
<script type="text/x-kendo-tmpl" id="teams">
    <div class="team" data-id="#:Team.Id#" data-year="@SeasonModel.Year">

        <img src="#:Team.Logo#" alt="#:Team.Name# image" />
        <h3>#:Team.Name#</h3>
        <p>Founded: #:Team.Founded#</p>
    </div>
</script>

@section scripts {
    <script src="~/js/league-details.js"> </script>
}

@section styles {
    <link rel="stylesheet" href="~/css/league-details.css" />
}

SoccerStatsNew/Views/League/Index.cshtml
@model IEnumerable<SoccerStatsData.LeagueModel>

<h3>League details</h3>

@foreach (var item in Model)
{
    <partial name="_MensLeague" model="@item" />
}

@section scripts {
    <script src="~/js/leagues.js"> </script>
    <script src="~/js/teams.js"> </script>
}

SoccerStatsNew/Views/League/Team.cshtml
@model SoccerStatsData.DtoModels.TeamDto
@{
    var TeamModel = Model.TeamModel.Team;
    var VenueModel = Model.TeamModel.Venue;
    var season = Model.Season;
}
<h1 class="h2" id="itemTitle">This is the display for @TeamModel.Name in @season</h1>

<kendo-tabstrip name="ajax-tabstrip">
    <items>
        <tabstrip-item text="Team" selected="true">
            <content>
                <partial name="_Team" model="@TeamModel" />
            </content>
        </tabstrip-item>

        <tabstrip-item text="Stadium" selected="false">
            <content>
                <partial name="_Stadium" model="@VenueModel" />
            </content>
        </tabstrip-item>
    </items>
</kendo-tabstrip>
<div class="mt-5">
    <kendo-button name="#players"
                  deferred=true
                  on-click="function(){ location.href = '/Player?team=@TeamModel.Id&season=@season' }"
                  icon="k-icon k-i-calendar">
        Team
    </kendo-button>
</div>


@section scripts {
    <script src="~/js/teams.js"> </script>
}

@section styles {
    <link rel="stylesheet" href="~/css/teams.css" />
}

SoccerStatsNew/Views/League/_League.cshtml
@model SoccerStatsData.TeamModel

<div>
    <div class="image custom-image">
        <img src="@Model.League.LogoURL" />
    </div>
    <div>
        <p>League: <span><b>@Model.League.Name</b></span></p>
        <p>Founded: <span><b>@Model.League.CountryName</b></span></p>
    </div>
</div>

<style>
    .custom-image {
        float: left;
    }
</style>

SoccerStatsNew/Views/League/_MensLeague.cshtml
@model SoccerStatsData.LeagueModel
@using UtilityLibraries

<div class="k-card k-card-horizontal">
    <div class="image">

        <img src="@Model.LogoURL" alt="not found" class="k-card-image" />


    </div>
    <div class="k-vbox k-column">
        <div class="k-card-header">
            <h5 class="k-card-title">@Model.Name</h5>
            <h6 class="k-card-subtitle">@Model.Type</h6>
            <h6 class="k-card-subtitle">@Model.CountryName</h6>
        </div>
        <div class="k-card-body">
            

        </div>
        <div class="k-card-actions k-card-actions-stretched k-card-actions-horizontal">
            @{
                // gives a unique name for each listview inside the league cards
                var listName = $"listView_{Model.LeagueId.ToString()}";
            }
            <span><b><i>select a season</i></b>
                @(Html.Kendo().DropDownList()
                    .Name(listName)
                    .DataTextField("Year")
                    .DataValueField("LeagueId")
                    .Events(e => e.Select("onSelect"))
                    .BindTo(Model.Seasons)
                    .Value("1")
                    .HtmlAttributes(new { style = "width: 100%" }))
            
            </span>
            
        </div>
       
    </div>
</div>

SoccerStatsNew/Views/League/_Stadium.cshtml
@model SoccerStatsData.TeamVenue

<div>
    <div class="image custom-image">
        <img src="@Model.Image" />
    </div>
    <div>
        <p>Stadium: <span><b>@Model.Name</b></span></p>
        <p>Surface: <span><b>@Model.Surface</b></span></p>
        <p>Capacity: <span><b>@Model.Capacity</b></span></p>
        <p>Address: <span><b>@Model.Address</b></span></p>
        <p>City: <span><b>@Model.City</b></span></p>

    </div>
</div>

<style>
    .custom-image {
        float: left;
    }
    
</style>

SoccerStatsNew/Views/League/_Team.cshtml
@model SoccerStatsData.TeamsPage
<div>
    <div class="image custom-image">
        <img src="@Model.Logo" />
    </div>
    <div>
        <p>Team: <span><b>@Model.Name</b></span></p>
        <p>Founded: <span><b>@Model.Founded</b></span></p>
        <p>Country: <span><b>@Model.Country</b></span></p>
        
    </div>
</div>

<style>
    .custom-image {
        float: left;
    }
</style>

SoccerStatsNew/Views/Player/Index.cshtml
@model SoccerStatsNew.Models.PlayerData

@{
    var line = string.Empty;
    using (StreamReader sr = new StreamReader("Views/Shared/_PlayerGrid.cshtml"))
    {
        line = sr.ReadToEnd();
    }
}
<h6>this is the players tab</h6>

@(Html.Kendo().Grid(Model.Response)
                .Name("player-grid")
                .Columns(columns =>
                {
                    columns.Bound(p => p.Player.Photo)
                           .Title("Player")
                           .Width(10);

                    columns.Bound(p => p.Player.Birth.Date)
                   .Title("Born")
                   .Width(5);

                    columns.Bound(p => p.Player.Age)
                   .Title("Age")
                   .Width(2);

                    columns.Bound(p => p.Player.Birth.Place)
                   .Title("Birth town")
                   .Width(5);

                    columns.Bound(p => p.Player.Nationality)
                   .Title("Nationality")
                   .Width(5);

                })
                .ClientRowTemplate(@line)
                .DataSource(dataSource => dataSource
                            .Ajax()
                            .Batch(true)
                            .PageSize(20)
                            .ServerOperation(false))
                .Pageable()
                .Sortable()
                .Scrollable(scr => scr.Height(430))
                .Selectable())

SoccerStatsNew/Views/Shared/_FixtureGrid.cshtml
<tr>
    <td>
        <img src="#:data.league.logo#" class="photo-badge home-badge">
        <span class="product-name">#:data.league.name#</span>
    </td>
    
    <td>
        <div class='pt-indicator' data-id='#:data.FixtureId#'>
            <span class="li-date">#= kendo.toString(kendo.parseDate(data.fixture.date), 'dd/MM/yyyy HH:mm') # </span>
        </div>
    </td>

    <td>
        <img src="#:data.teams.home.logo#" class="photo-badge home-badge">
        <span class="product-name">#:data.teams.home.name#</span>
    </td>
    <td>
        <img src="#:data.teams.away.logo#" class="photo-badge home-badge">
        <span class="product-name">#:data.teams.away.name#</span>
    </td>

    <td>
        <span>#:data.league.round# </span>
      
    </td>

</tr>

SoccerStatsNew/Views/Shared/_IndividualTeam.cshtml
@model SoccerStatsData.RequestModels.PredictionRequestFiles.Team

<div class="badge-name">
    <img src="@Model.Logo" class="rounded photo-badge home-badge">
    <span>@Model.Name</span>
</div>

SoccerStatsNew/Views/Shared/_LastFiveGrid.cshtml
<tr>
    <td>
        <img src="#:data.League.Logo#" class="photo-badge home-badge">
        <span class="product-name">#:data.League.Name#</span>
    </td>

    <td>
        <div class='pt-indicator' data-id='#:data.Fixture.FixtureId#'>
            <span class="li-date">#= kendo.toString(kendo.parseDate(data.Fixture.Date), 'dd/MM/yyyy') # </span>
        </div>
    </td>

    <td>
        <span class="li-date">#= kendo.toString(kendo.parseDate(data.Fixture.Date), 'HH:mm') # </span>
    </td>

    <td>
        <div>
            #:data.Fixture.Venue.Name#
        </div>
    </td>

    <td>
       <div>
            #:data.Fixture.Referee#
       </div>
    </td>

    <td>
        <div class="product-name">
            <img src="#:data.Teams.Home.Logo#" class="photo-badge home-badge">
            <span>#:data.Teams.Home.Name# <b>#:data.Goals.Home#</b></span>
            <span><b>:</b></span>
            <img src="#:data.Teams.Away.Logo#" class="photo-badge">
            <span>#:data.Teams.Away.Name# <b>#:data.Goals.Away#</b></span>
        </div>
    </td>
</tr>

SoccerStatsNew/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoccerStatsNew</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/kendo/styles/kendo.default-v2.css" />
    <link rel="stylesheet" href="~/css/site.css"  />
   
    @RenderSection("styles", required: false)

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/kendo/js/kendo.all.min.js"></script>
    <script src="~/lib/kendo/js/kendo.aspnetmvc.min.js"></script>
    <script src="~/js/site.js" ></script>
    @Html.Kendo().DeferredScripts();
    @RenderSection("scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SoccerStatsNew</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SoccerStatsNew - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
</body>
</html>

SoccerStatsNew/Views/Shared/_LeagueTableGrid.cshtml
<tr class="table_font_size table_nowrap">
    <td>
        <span><b>#:data.rank#</b></span>
        <span><img src="#:data.team.logo#" class="table_logo"></span>
        <span><b>#:data.team.name#</b></span>
    </td>
    <td>
        <span><b>#:data.all.played#</b></span>
    </td>
    <td>
        <span><b>#:data.all.win#</b></span>
    </td>
    <td>
        <span><b>#:data.all.draw#</b></span>
    </td>
    <td>
        <span><b>#:data.all.lose#</b></span>
    </td>
    <td>
        <span><b>#:data.all.goals.for#</b></span>
    </td>
    <td>
        <span><b>#:data.all.goals.against#</b></span>
    </td>
    <td>
        <span><b>#:data.goalsDiff#</b></span>
    </td>
    <td>
        <span><b>#:data.points#</b></span>
    </td>
    <td>

        # for (var k = 0; k < data.FormChars.length; k++) 
        { #
            # if (data.FormChars[k] == 'W' ) 
            {#
                <span class="wg_form wg_form_win">W</span>#
            }#
            
            # if (data.FormChars[k] == 'L' )
            {#
                <span class="wg_form wg_form_lose">L</span>#
            }#

            # if (data.FormChars[k] == 'D' )
            {#
                <span class="wg_form wg_form_draw">D</span>#
            }#

        # } #
        
    </td>
</tr>

SoccerStatsNew/Views/Shared/_PlayerGrid.cshtml
<tr>
    <td>
        <img src="#:data.player.photo#" class="photo-badge home-badge">
        <span class="badge-name">#:data.player.firstname# #:data.player.lastname#</span>
    </td>

    <td>
        <span class="badge-name">#:data.player.birth.date#</span>
    </td>
    <td>
        <span class="badge-name">#:data.player.age#</span>
    </td>
    <td>
        <span class="badge-name">#:data.player.birth.place#</span>
    </td>

    <td>
        <span class="badge-name">#:data.player.nationality#</span>
    </td>


</tr>

SoccerStatsNew/Views/Test/Index.cshtml
<div id="wg-api-football-standings"
     data-host="v3.football.api-sports.io"
     data-key="3f9914c1b38c709f55114e30991a308b"
     data-league="41"
     data-team=""
     data-season="2022"
     data-theme=""
     data-show-errors="false"
     data-show-logos="true"
     class="wg_loader">
</div>
<script type="module"
        src="https://widgets.api-sports.io/2.0.3/widgets.js">
</script>